# Generated by Django 2.2.20 on 2021-05-23 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='post-photos/%Y/%m/%d')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('card_description', models.CharField(default='somevalue', max_length=300)),
                ('body', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='projects-photos/%Y/%m/%d')),
                ('project_description', models.CharField(max_length=200)),
                ('code_link', models.CharField(max_length=300)),
                ('demo_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='OpenSource',
        ),
    ]
