# Generated by Django 2.2.19 on 2021-03-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210320_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='img',
            new_name='image',
        ),
    ]
