# Generated by Django 2.2.19 on 2021-03-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210321_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='githuburl',
        ),
    ]
