# Generated by Django 2.2.20 on 2021-04-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20210418_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.FilePathField(blank=True, null=True, path='/img'),
        ),
    ]
