# Generated by Django 2.2.20 on 2021-04-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.FilePathField(blank=True, null=True, path='/media'),
        ),
    ]
