# Generated by Django 2.2.20 on 2021-04-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20210418_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='http://127.0.0.1:8000/media/photos/%Y/%m/%d'),
        ),
    ]
