# Generated by Django 2.2.20 on 2021-04-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20210424_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='card_description',
            field=models.CharField(default='somevalue', max_length=300),
        ),
    ]
