# Generated by Django 2.2.20 on 2021-04-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20210427_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
