# Generated by Django 2.2.20 on 2021-04-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_project_repo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
