# Generated by Django 2.2.20 on 2021-04-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='projects-photos/%Y/%m/%d')),
                ('project_description', models.CharField(max_length=200)),
                ('code_link', models.CharField(max_length=300)),
                ('demo_link', models.CharField(max_length=300)),
            ],
        ),
    ]
