# Generated by Django 2.2.20 on 2021-05-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
